name: build_project
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      run: make setup
      run: make test 
      run: make lint


